### ISSUE TITLE
Login works after scopes were fixed but icare gives me an error after auth succeeds

### ISSUE THREAD

**Issue by tistudios** [diowa/icare#134]
#114 Following on from my response, here's the issue I'm facing after updating scopes.
![screen shot 2019-02-06 at 12 26 41 pm](https://user-images.githubusercontent.com/39240982/52361234-c040f480-2a0b-11e9-8e26-4f8134975ed8.png)

**Comment by tagliala** [comment]
Hi, please check the logs `heroku logs`, they will contain more information

**Comment by tistudios** [comment]
![screen shot 2019-02-06 at 12 56 45 pm](https://user-images.githubusercontent.com/39240982/52362513-c08ebf00-2a0e-11e9-8d90-0c00f811c458.png)

MongoDB invalid db name. I will take a look at app/models/user.rb and see if i can make sense of this.

**Comment by tagliala** [comment]
Please check that you are using `mongolab` addon

```
$ heroku addons

Add-on                                Plan     Price  State  
────────────────────────────────────  ───────  ─────  ───────
mongolab (x-y-z)         starter  free   created
 └─ as MONGOLAB
```

And you have a valid MONGODB_URI environment variable

```
$ heroku config:get MONGODB_URI
mongodb://...
```

⚠️ **ATTENTION** DO NOT copy the content of your variable here

**Comment by tistudios** [comment]
Ah! I had created the heroku app through the generic cli & without following the guide in the wiki. Thanks I will do this and report back.

**Comment by tistudios** [comment]
Fixed it perfectly!
