### ISSUE TITLE
docker doesn't work

### ISSUE THREAD

**Issue by kercos** [diowa/icare#1486]
Hi,

I'm trying to run the app via Docker.

```
cp docker/icare/variables.env.example cp docker/icare/variables.env
docker-compose up
```
and i get the following:
```
failed to solve: failed to compute cache key: failed to calculate checksum of ref 57bd6280-134c-4f3b-a04a-f6a5113a0bfa::td9994vlz68k9nyki8qubrdy9: "/babel.config.js": not found
```

Any help is appreciated!

**Comment by tagliala** [comment]
Hi, thanks for your interest in icare

As per the [Docker section in the Readme](https://github.com/diowa/icare#docker-experimental),

> ### Docker (Experimental)
> 
> Experimental Docker support. **Please do not ask for support, PR to improve the current implementation are very welcomed.**

(**emphasis** mine)
