### ISSUE TITLE
Auth0 - invalid credentials

### ISSUE THREAD

**Issue by zdenek-brhel** [diowa/icare#1513]
Hello,

I'm trying to setup this application. I followed [the tutorial](https://github.com/diowa/icare/wiki/Setup-Auth0-App).
I have managed to run the application and I got to the point of viewing the main page:
![image](https://github.com/diowa/icare/assets/141405044/6cbba0e0-59f6-4f17-9944-37886545c557)

However, as seen in upper right corner, whenever I try to login, it results in "Invalid credentials" error. When I login, it redirects me to Auth0 login (which as I reckon is correct), I either input my credentials or create new user (result is same). After that, I am redirected back and only thing that happens is shown on the image. I figured out I need to switch to "Classical login", as the new one doesn't support the code editing mentioned on project Wiki, but again - same result.

The only thing I can think of as the potential problem is that I am running the application on localhost, meaning I added `https://localhost:3443/users/auth/auth0/callback` to Allowed callbacks URLs and `https://localhost:3443/` to Allowed web origins, but maybe that's not the problem.

Is there anything else I need to do? Is there a way to access the website without Auth0 login?

Thank you for your help!

**Comment by tagliala** [comment]
Hi, thanks for your interest in icare.

I've just updated the wiki and I can confirm that it works both on `http://localhost:3000` and on `https://localhost:3443` (via docker)

> I figured out I need to switch to "Classical login"

Not needed, please check the new wiki: https://github.com/diowa/icare/wiki/Setup-Auth0-App

Some notes:
- Please check `set :base_url, 'localhost:3000'` configuration. It should be `localhost:3443` for your use case
- Please remember that the first time a user needs to "Sign Up" and then they can login. You can see registered users in `User Management -> Users` on Auth0

**Comment by zdenek-brhel** [comment]
Hello, thank you for your response. I have followed new wiki and it solved my problem. Thank you for your help!
