### ISSUE TITLE
Public Transports in the search section

### ISSUE THREAD

**Issue by marchions** [diowa/icare#28]
Hi,
I want to know if it is possible to visualize also public transports (google maps support it) in the "search section" (for instance when there are not itineraries created by users) in some way...
I know that not it is not implemented in your app, but I only want to know if it is possible, and what is the way needed (part to change) to achieve this point (I guess it is only a configuration point).

Really thank you in advance.

Matteo

**Comment by tagliala** [comment]
Sorry for the late reply, I'm trying to close old issues.

At the moment we are not interested in this feature. Maybe in the future we could reconsider
