### ISSUE TITLE
[Feature Request] Breake free from Facebook 

### ISSUE THREAD

**Issue by kirantpatil** [diowa/icare#329]
Hello,

Say no to Facebook and make this app Facebook free.

Also donot attach it to any other Big corps like Google, Amazon and Facebook.

Since it is a privacy and too much centralization issue on single platform.

Thanks.

**Comment by tagliala** [comment]
Hi,

thanks for the suggestion.

icare *is* Facebook Free. We use devise authentication, and Facebook is just a showcase for an omniauth provider.

With the help of a Rails developer, you can switch to every provider you need or go back to a plain username-password authentication.

At the moment we are not interested in providing username-password authentication for this demo 

Ref: https://github.com/diowa/icare/issues/231#issuecomment-526561101

Hope it helps

Closing here
