### ISSUE TITLE
Giving error after facebook login: Users::OmniauthCallbacksController#facebook

### ISSUE THREAD

**Issue by mohdbashir** [diowa/icare#34]
NoMethodError in Users::OmniauthCallbacksController#facebook
undefined method `gsub' for nil:NilClass
Extracted source (around line #21):

          # Locale, with priority to application setting
          self.locale = auth.extra.raw_info.locale.gsub(/_/,'-') unless self.locale?

          # Username and uid array
          self.username_or_uid = [ username, uid ]

Rails.root: /home/thtechonline/public_html/icare

**Comment by kranidiotis** [comment]
I have the same problem 

NoMethodError in Users::OmniauthCallbacksController#facebook
undefined method `gsub' for nil:NilClass
Extracted source (around line #21):
# Locale, with priority to application setting
self.locale = auth.extra.raw_info.locale.gsub(/_/,'-') unless self.locale?
# Username and uid array
self.username_or_uid = [ username, uid ]

**Comment by cnacorrea** [comment]
I think I have the exact same issue. Anybody had any luck with it? Best!

**Comment by tagliala** [comment]
Sorry for the delay. I will take a look

**Comment by tagliala** [comment]
So there are people from facebook **without** a locale. I don't know how this is possible but that's fine :)

**Comment by tagliala** [comment]
There are some errors in the facebook authentication that we didn't notice in specs

I need to fix this
