### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by arestep42** [diowa/icare#341]
Hi! My College Software Engineering group are trying to implement this project to work on our campus. Unfortunately, we are unable to get the search function to work like it does in the demo version. Have you run into this problem before and could you offer any solutions that we should look into?

**Comment by tagliala** [comment]
Hi!

Thanks for your interest in our project. Maybe it is related to google maps api key configuration? Please provide as more details as possible

Please check those wikies:
- https://github.com/diowa/icare/wiki/%5BW.I.P.%5D-Developing-icare-on-Debian---Ubuntu
- https://github.com/diowa/icare/wiki/Deploy-on-Heroku#the-hard-way

**Comment by tagliala** [comment]
Closing here
