### ISSUE TITLE
Deploying on Heroku

### ISSUE THREAD

**Issue by cnacorrea** [diowa/icare#35]
Hi,

I just followed all instructions for deploy on Heroku and launching the Facebook app. All went ok, but when I try to login with some Facebook account, it says "there was an error" and gets back to the initial screen.
I'd like to host the app as voluntary work in an religious event. The event will happen by late october, and would be willing to pay for your hosting if it was in the range for mere mortals. My mail address is carlos.nilton at gmail

Best and cheers for your app!

**Comment by tagliala** [comment]
Hi,

sorry for the late reply

Please take a look here: https://github.com/diowa/icare/wiki/Setup-Facebook-App

Probably this wiki should be updated. Feel free to edit the guide or asking questions if you need more info

**Comment by tagliala** [comment]
There are issues with deploy on heroku and facebook, I need to investigate further

**Comment by tagliala** [comment]
It should be ok now
