### ISSUE TITLE
Heroku issue setting up environment

### ISSUE THREAD

**Issue by ametzler33** [diowa/icare#36]
Hi, Every time I try to deploy to Heroku, I get the following message: 
There was an issue setting up your app environment.
Couldn't find either the add-on service or the add-on plan of "newrelic:stark".
Any ideas how I can fix this?

**Comment by tc6soccer** [comment]
No sorry

**Comment by tagliala** [comment]
Thanks for reporting this

Apparently newrelic changed their addons.

 I will fix this asap

**Comment by tagliala** [comment]
Done, thanks!

**Comment by ametzler33** [comment]
Brilliant, Thanks a lot :)

**Comment by ametzler33** [comment]
I was wondering, does icare have some kind of cms module to change the basics?
I’m pretty shitty with coding so I’m trying to figure out the best way to do small modifications.

Brgds,
Antoni

**Comment by tagliala** [comment]
Sorry, it doesn't at the moment.

You need css (scss) and html (slim) basics to customize icare

**Comment by ametzler33** [comment]
Hi Geremia,

Sorry for the late response, I’ve taken a look but I couldn’t figure out how to adapt some of the things.
I’m wondering, does your company offer the possibility of modifying a few things for me?
If so, how much would that cost?

Brgds,
Antoni
