### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by ametzler33** [diowa/icare#37]
Whenever I try to login to both my and the demo version I get the following error:
<img width="702" alt="screen shot 2015-10-16 at 11 48 47" src="https://cloud.githubusercontent.com/assets/13383861/10538922/31237ce6-73fc-11e5-8ab2-3efb5c0337fe.png">

I would very much appreciate your help.

**Comment by kirantpatil** [comment]
Yes, please fix the demo settings.

**Comment by tagliala** [comment]
Thanks for reporting this. Sorry for the inconvenience. I will work on this during the weekend

**Comment by tagliala** [comment]
We are experiencing an issue with some of our products related to mongodb, mongolab and heroku

**Comment by tagliala** [comment]
Sorry but I didn't have time to fix this

**Comment by ametzler33** [comment]
Hi, Thanks for the updates. Do you know by when you might be able to get this running again?

**Comment by tagliala** [comment]
I **must** do this ASAP. It does not happen on local environment or Travis CI (just run the build again to be sure: https://travis-ci.org/diowa/icare/builds/82217873)

@ametzler33 if you could setup a new app and use the "deploy to heroku" button I think it should work. I would appreciate if you let me know

**Comment by ametzler33** [comment]
I setup everything from the beginning and used the deploy to Heroku button, unfortunately it didn't work.

**Comment by tagliala** [comment]
So apparently we needed to update to mongoid 5 because of MongoLab support on heroku.

I thought it was painful, I was wrong.

icare is back, thanks! <3
