### ISSUE TITLE
Facebook login is broken, is there no alternative?

### ISSUE THREAD

**Issue by stusherwin** [diowa/icare#371]
When I click the `Login with Facebook` button on icare.diowa.com I get this error:

![image](https://user-images.githubusercontent.com/606984/72430560-9d29d380-378a-11ea-85a1-4c1d28b2e1e0.png)

Is there no way to log in and demo the app without Facebook?

**Comment by tagliala** [comment]
Hi, thanks for trying icare

I've got the issue. Apparently, Facebook API do not allow to get user's email address anymore.

> Is there no way to log in and demo the app without Facebook?

At the moment there isn't

Me and @cesidio would like to create a demo SSO and use it with icare, I think this is a good opportunity and finally say goodbye to Facebook

**Comment by tagliala** [comment]
@stusherwin I've pushed a fix and now facebook login should work again.

Could you please give another try?

**Comment by tagliala** [comment]
Facebook does not allow unpublished apps to get email.

We want to implement an example SSO and remove facebook completely

**Comment by Asimov4** [comment]
You could try https://auth0.com/ (free for up to 7000 users)

**Comment by tagliala** [comment]
@Asimov4 

It took a lot of time, but I've removed Facebook from icare in favor of Auth0, thanks for the suggestion 🎉 

(I'm quite happy of this change: this step was required before deleting my Facebook account 😊)

I've updated the wiki page and provided instructions on how to create a tenant and a working example

https://github.com/diowa/icare/wiki/Setup-Auth0-App

**Comment by Asimov4** [comment]
Amazing! Thank you!
