### ISSUE TITLE
One-click Deploy to Heroku not working.

### ISSUE THREAD

**Issue by netcyrax** [diowa/icare#45]
I tried to deploy to Heroku but it failed with the following error message:

> -----> Preparing app for Rails asset pipeline
>        Running: rake assets:precompile
>        rake aborted!
> 
> Airbrake::Error: the 'default' notifier isn't configured
> [...]
> Airbrake::Error: the 'default' notifier isn't configured
> [...]
> Airbrake::Error: both :project_id and :project_key are required
> [...]
> Tasks: TOP => assets:precompile => assets:environment
>  !
>  !     Precompiling assets failed.
>  !
>  !     Push rejected, failed to compile Ruby app

The Airbrake related attributes are marked as optional. Any help would be appreciated.

**Comment by tagliala** [comment]
Thanks for reporting this.

This problem slightly depends on Airbrake 5.0 which doesn't allow for nil parameters as a fallback for "disable airbrake" as in 4.0.

This should be addressed on the current master branch of `airbrake-ruby` via https://github.com/airbrake/airbrake-ruby/pull/75

I don't want to use the master branch of airbrake so you can use this branch if you want to deploy icare until the next version of airbrake-ruby comes out: https://github.com/diowa/icare/tree/airbrake-workaround-temp

**Unfortunately** this still doesn't work. I'm having troubles with the mongoid rake task. I'm taking a look but I'm unable to replicate this in my development machine

**Comment by tagliala** [comment]
Fixed in 0.37.1, thanks!

**Comment by netcyrax** [comment]
Thanks for the super fast fix! :)

Just letting you know that the deployment is still unusable due to https://github.com/diowa/icare/issues/41

**Comment by tagliala** [comment]
thanks, didn't know it is unusable. I will try to configure a new app. Let's use #41
