### ISSUE TITLE
Problems with OmniauthCallbacksController

### ISSUE THREAD

**Issue by danlorry** [diowa/icare#47]
Now I have this error:

Mongo::Error::NoServerAvailable in Users::OmniauthCallbacksController#facebook
No server is available matching preference: #<Mongo::ServerSelector::Primary:0x94960320 tag_sets=[] server_selection_timeout=30 local_threshold=0.015>

Extracted source (around line #114):
  def self.from_omniauth(auth_hash)
    where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create do |user|
      user.email = auth_hash.info.email
      user.image = auth_hash.info.image
      user.name  = auth_hash.info.name

**Comment by tagliala** [comment]
are you using the "deploy on heroku" button? Could you please provide me more information?

**Comment by danlorry** [comment]
No, I'm using cloud 9. When I push the button login with facebook I find
this error:

[image: Imágenes integradas 1]

2016-05-26 16:53 GMT+02:00 Geremia Taglialatela <notifications@github.com>:

**Comment by tagliala** [comment]
Can't see the image, please update it on github. Sorry but I don't know how to help on cloud9. Please notice that you need a working mongodb server as well as redis

**Comment by danlorry** [comment]
![image](https://cloud.githubusercontent.com/assets/3596327/15579514/45e2de4c-2365-11e6-95ea-ea49b5e63b11.png)

**Comment by tagliala** [comment]
please make sure you have a working and well configured mongodb server

**Comment by danlorry** [comment]
Ok, that was the problem, thanks

**Comment by tagliala** [comment]
you're welcome.

Closing here

**Comment by tagliala** [comment]
@danlorry feel free to start a wiki on how to deploy on cloud9
