### ISSUE TITLE
Application doesn't work after making changes to config/settings/application.rb file

### ISSUE THREAD

**Issue by kalyanadupa** [diowa/icare#50]
Hi, I need to override the defaults in the application.rb file such as "app name", currency, fuel consumption. 
But after making the necessary changes and deploying the app it doesn't allow new users to create the account. It shows the **flash.sessions.error.create** error on the app home page. 

Do I have to configure these changes in the local.rb file instead even if it is not sensitive data.

**Comment by tagliala** [comment]
> Do I have to configure these changes in the local.rb file instead even if it is not sensitive data.

No, you don't. The local.rb file is not deployed nor committed to the repository.

This issue seems due to a wrong facebook configuration, please check the application log

**Comment by tagliala** [comment]
Closing here
