### ISSUE TITLE
How to setup Google Maps API

### ISSUE THREAD

**Issue by chanyut** [diowa/icare#57]
I have deployed icare on Heroku, everything fine, but Google map cannot be loaded due to Missing API Key error. I also tried to add Config var "GOOGLE_MAPS_API_KEY" but the result is still the same.

**Comment by tagliala** [comment]
I'm going to edit https://github.com/diowa/icare/wiki/Deploy-on-Heroku

**Comment by tagliala** [comment]
@chanyut thanks.

There was an issue in the code and I've fixed and updated all the wikis

I've also tried to deploy with the heroku button and everything went fine

**Comment by chanyut** [comment]
@tagliala Thank you so much, right now I can deploy on Heroku, and everything is fine. You save my day 👍

**Comment by tagliala** [comment]
@chanyut you're welcome. Thanks for reporting this issue
