### ISSUE TITLE
Cannot deploy on Heroku

### ISSUE THREAD

**Issue by lex90210** [diowa/icare#59]
Hi @tagliala 

I have deployed your app successfully once before and had to do a fresh redeployment just yesterday but this time it failed to successfully be deployed on Heroku (the build fails). Not sure why, I put in all the variables required correctly. Could you give this a look? Much appreciated. 

Just to add: Great work on the app. You may know this already but your app is saving a lot of peoples time, money and to add, the environment. Well thought out.

**Comment by tagliala** [comment]
Hi @lex90210 

> I have deployed your app successfully once before and had to do a fresh redeployment just yesterday but this time it failed to successfully be deployed on Heroku (the build fails). Not sure why, I put in all the variables required correctly. Could you give this a look? Much appreciated.

Could you please provide more details?

> Just to add: Great work on the app. You may know this already but your app is saving a lot of peoples time, money and to add, the environment. Well thought out.

Thanks 💚

**Comment by tagliala** [comment]
Got it. It is the Airbrake configuration

**Comment by tagliala** [comment]
Fixed, thanks

**Comment by lex90210** [comment]
You're the best @tagliala 
Deployed perfectly. 

If I could chip in just one more question... How do I change the default map coordinates and apply restrictions on iteneraries? Tried doing this from the application.rb file in the settings folder and it had no effect.

**Comment by tagliala** [comment]
> How do I change the default map coordinates 

@lex90210 I've just noticed that I should fix that part. This was done in the commercial application. I will do that in a short while

> How do I change the default map coordinates and apply restrictions on itineraries?

You should be able to restrict itineraries in a given (rectangular) area by setting `:geo_restricted` to true and `:bounds => :sw`, `:bounds => :ne` in `application.rb`. Please remember that you should deploy after changed that file

https://github.com/diowa/icare/blob/master/config/settings/application.rb#L55

AFAIK, geo restricted itineraries works. Relevant specs: https://github.com/diowa/icare/blob/master/spec/models/itinerary_spec.rb#L92

**Comment by tagliala** [comment]
@lex90210 you should be able to config the center point of your map and the zoom level with the following configuration settings:
https://github.com/diowa/icare/blob/0.53.5/config/settings/application.rb#L45
https://github.com/diowa/icare/blob/0.53.5/config/settings/application.rb#L46

**Comment by lex90210** [comment]
Hey thanks a million for the responses. I'll give these a go now. Cheers
