### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by lex90210** [diowa/icare#60]
Hi @tagliala 

Thanks for the assist the last time. Just a few questions I need clarifications on:

1. In account settings, it states "we will send emails at the following address" - but no email address is listed and there is no input for an address. Is this a future feature to be implemented or is the users registered email on facebook the address of contact?
2. Does the mailer work if configured correctly in the settings?
3. Regarding facebook details, If I am right, the advanced search works dependent on details pulled from users public profile. From my understanding public_profile details are approved by default by facebook, but on my profile and other test profiles, the user gender fails to display. Any ideas on what could be causing this?
All I get is the profile picture, username and a likes/interest list (I thought the likes/interest list required approval to be displayed)
4. Does the verified user display require approvaal from facbook or is this approved by default as I also don't see this displayed on my test profiles.

Appreciate any assist as always. 
Regards

**Comment by tagliala** [comment]
Hi

> 1. In account settings, it states "we will send emails at the following address" - but no email address is listed and there is no input for an address. Is this a future feature to be implemented or is the users registered email on facebook the address of contact?

Not implemented. Also, some users register via mobile phone so we don't have an email coming from facebook

> 2. Does the mailer work if configured correctly in the settings?

Sorry, I don't know.

> 3. From my understanding public_profile details are approved by default by facebook, but on my profile and other test profiles, the user gender fails to display. Any ideas on what could be causing this?

Fetching extra date is done by a background job. Running background job is not possible on the free tier of heroku, so icare uses a [hack to run resque inside a web process](https://github.com/diowa/icare/blob/master/config/unicorn.rb#L16). Maybe there are issues with this, but this is something I'm not interested in investigating at the moment. PR are welcome

> 4. Does the verified user display require approvaal from facbook or is this approved by default as I also don't see this displayed on my test profiles.

Maybe the same issue as before. PR are welcome

Hope it helps.

Closing here but feel free to comment

**Comment by lex90210** [comment]
Thanks for the response, totally understand. I'll look in the Facebook issues and let you know what I find.

Regards

**Comment by lex90210** [comment]
Hi @tagliala ... So I tried looking into the issue of the app not retrieving basic profile details and came short. One thing I noticed was I had the worker dyno off on Heroku but when I got it on, it didn't really solve the issue as I hoped. Just a quick one, would you be willing to help sort this out for a fee? I can pay for the service if need be as I would love your work complete for a better experience. 

Thanks and regards.
