### ISSUE TITLE
how does it work?

### ISSUE THREAD

**Issue by AntonioS30** [diowa/icare#61]
Hi i cannot understand how to setup this wonderful project.
I've only worked with cms joomla on a apache server.... where can i find how to setup and work with your work? Thank you

**Comment by tagliala** [comment]
Hi Antonio,

this is a web application based on Ruby on Rails.

If you just want to deploy this application, you need basic Heroku knowledge

If you want to customize look & feel or add new features, you need knowledge of the tecnologies listed in our readme: https://github.com/diowa/icare#icare

Please also check out our wiki:
https://github.com/diowa/icare/wiki/%5BW.I.P.%5D-Developing-icare-on-Debian---Ubuntu
https://github.com/diowa/icare/wiki/Deploy-on-Heroku

Hope it helps, closing here.

Edits to our wiki are welcomed as well as suggestion to improve documentation

**Comment by AntonioS30** [comment]
there is a mode to work on windows/apache php? or server linux?

**Comment by tagliala** [comment]
> there is a mode to work on windows/apache php? 

Nope, PHP is a completely different language. You should port the back end to PHP

> or server linux?

Yes, you need a linux server with ruby, rubygems, mongodb and some other stuff you could find in our wiki
