### ISSUE TITLE
Suggestion / request: use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [diowa/icare#66]
First of all, thanks for icare!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/icare/pulls). I'll port the `capybara` one across to this repo now. @tagliala, it looks like you're the one who's kept on top of dependency updates, so perhaps you're best placed to review?

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. I'd love any feedback, and obviously having open source repos using Dependabot helps boost its profile, but if it's not helpful to you then it's not really worth anything.

You can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot) if you decide to give it a try. It's been through GitHub's security testing (to be allowed in the GitHub Marketplace) and is used by a few thousand organisations, and the source code is [here](https://github.com/dependabot/dependabot-core).

:octocat:

**Comment by tagliala** [comment]
Hi @greysteil , thanks for this suggestion.

I was waiting for such a tool and I appreciate your work. I've configured a couple of open source repositories

**Comment by tagliala** [comment]
Done

**Comment by greysteil** [comment]
Awesome, thanks @tagliala! Looks like the first round of PRs were all useful, but feel free to ping me if there's ever anything it could do better.
