### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Mughira** [diowa/icare#850]
Hi, I am new in Ruby. I have been trying to setup the app in my local machine but its giving me error whenever I run the command.
Can you guy's explain in steps, like how to setup and run this application.

rails s -b 'ssl://0.0.0.0:3443?key=docker/nginx/ssl/app_key.pem&cert=docker/nginx/ssl/app_cert.pem'

Thanks in advance.

![Screenshot 2021-08-11 142731](https://user-images.githubusercontent.com/41149339/129005085-6973e0fe-db0b-4f3f-ad27-722701b35ec2.png)

**Comment by tagliala** [comment]
Hi,

I'm leaving this open for feedback from the community, but we do not actually support windows

I think it could be the `&` char in the string. Please try with double quotes instead of quotes. Let me know

```
rails s -b "ssl://0.0.0.0:3443?key=docker/nginx/ssl/app_key.pem&cert=docker/nginx/ssl/app_cert.pem"
```

PS:

I think you can also start and develop without SSL on localhost by running `rails s`

**Comment by Mughira** [comment]
Hi, It's still giving me the error. I am not sure.
Should I install Linux and than run this on it.

![image](https://user-images.githubusercontent.com/41149339/129012084-0b4c20cd-1ee2-4876-9409-c597d6681901.png)

-> I have one more question.
We were actually looking for a ride sharing app, and we got to know about your opensource code. 
I am confused about one feature. 
Like how rider and driver get's connected. I mean is this app matches the rider and driver route.? or some other logic.?
 
Thanks in Advance.

**Comment by tagliala** [comment]
> Hi, It's still giving me the error. I am not sure.

That's another error, there is a gem missing.

We have instructions for Ubuntu https://github.com/diowa/icare/wiki/Developing-icare-on-Debian-Ubuntu, but many of the things also apply on windows

> Like how rider and driver get's connected. I mean is this app matches the rider and driver route.? or some other logic.?

Simple geographic matching on start and destination + date

You can find the logic here: https://github.com/diowa/icare/blob/main/app/services/itinerary_search.rb

**Comment by Mughira** [comment]
Oh, I get it.
Thanks a lot.

**Comment by tagliala** [comment]
Welcome, feel free to ask more questions

**Comment by Mughira** [comment]
If I have to change the logic from "geographic matching on start and destination + date" to "geographic route matching + date".
Should I just change this file.?
And is it run on Android and IOS, or do I have to develop something different for them.

**Comment by tagliala** [comment]
> geographic route matching

That's a different approach, you need to change the logic. This is a good starting point: https://github.com/rgeo/rgeo

> And is it run on Android and IOS, or do I have to develop something different for them.

If you want native app, you should transform icare into an API, it is not so hard with Rails, and develop apps to consume the APIs

**Comment by Mughira** [comment]
Okay,
Sound good.
I guess will have to do some R&D before starting.

Thanks.
